### ISSUE TITLE
Widget image-uploader output/url only works for <img /> src attribute.

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/admin-pages#116]
If one tries to use the output/url of the widget as ```style={{ backgroundImage: `url('${value}');` }}``` or within a responsive image markup using `srcset` or `xlinkHref` on a clipPath setup, the image will not be served properly.

As far as we tested the output/url only works for `<img src={value} />`.

We follow the url generated url in one of these cases and got the following error:

![bug-vtex-filesystem](https://user-images.githubusercontent.com/1207017/49804003-9e433280-fd38-11e8-99cb-de6dd78f8720.png)

## Expected Behavior

```<div style={{ backgroundImage: `url('${value}');` }} />``` should work as expected.

## Current Behavior
The image url throws an error.

## Possible Solution
?

## Steps to Reproduce (for bugs)
```<div style={{ backgroundImage: `url('${value}');` }} />```

## Your Environment
* macOS Sierra 10.12.6
* Google Chrome Latest
* Desktop
* homolog--nerdaocubo.myvtex.com

**Comment by alcar** [comment]
Hey, @juliomoreira! Sorry for the late reply.

I've just tried uploading an image and setting its URL as the background image of a `div` element, and it worked.

Since this issue is a few months old, I'm closing it for now, but please let us know if the problem persists.
