### ISSUE TITLE
Discussion to refactor project structure

### ISSUE THREAD

**Issue by thiagomurakami** [vtex-apps/admin-pages#126]
First I will list some issues so we can discuss the solutions afterwards...

## I. No distinction between containers and components
This (kinda old) [post](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) by Dan Abramov explains the concept. Briefly, containers have most business logic/data fetching, etc, whereas components are more visual...

Why I think this is important:
1. Testability: Components are way easier to test this way.
2. Separation of concerns: Nowadays we have components that simply do too much.
3. Easier to find important files to debug/implement new features.

I'm not sure what is the best way to implement this, I can think of some options:
1. Create a separate folder for each:
The problem with this approach is that we may end up with files with the same name...
```
components/
 | Editor.tsx
containers/
 | Editor.tsx
```

2. Use some kind of suffix on the container name
But where should we put these files?

3. Why not both? 🌮™️
The problem with this is that the names become kinda redundant...
```
components/
 | Editor.tsx
containers/
 | EditorContainer.tsx || Editor.container.tsx || Editor-container.tsx
```

## II. Create another layer of separation by domain/feature
I think it makes sense to have another layer on top of the current "structure". So instead of:
```
components/
queries/
typing/
utils/
```

We would have:
```
ComponentsEditor/
 | components/
 | queries/
 | typing/
 | utils/
```

This makes it easier to:
1. Discover where each files/component is used.
2. Less folders open on the editor/IDE sidebar 😛(This may seem minor, but it's important)
3. (In the future) Have separate test coverage rules... For example, folders that are used across multiple domains like `(root)/shared/` or even `(root)/components/` (if we decide to have those) could have high test coverage rules (80%+?) whereas newer modules don't need to be so strict.

## III. `*.test.ts(x)` in favor of `__tests__`
This makes `import`s easier and you don't need to replicate your entire project inside `__tests__/` (or `test/`).

Example of such replication:
[https://github.com/reduxjs/redux/tree/master/src](https://github.com/reduxjs/redux/tree/master/src)
[https://github.com/reduxjs/redux/tree/master/test](https://github.com/reduxjs/redux/tree/master/test)

## IV. `package.json` in favor of `index.js`
By using `package.json` you can set the `"main"` file that is imported when importing the folder, thus, eliminating the need for a `index` file.

At least, I don't think `index.*` should have any logic/component, it should simply be a `import`/`export` file, because it really makes no sense to have multiple tabs with the same filename open.
___

There are some suggestions for each issue, but that's all they are, suggestions.

Also, if you think that some problems I listed don't make sense, we should discuss it here!

So... WDYT?

**Comment by alcar** [comment]
> ## I. No distinction between containers and components

I like using `index` files for containers and, when components are also needed, I name them something else, e.g. `List`, `Card`, etc. I understand that having multiple `index` files in the same project may be a little confusing at times, but `import List from './List/List.tsx'` is worse IMHO.
 
> ## II. Create another layer of separation by domain/feature

I'm not sure I understood what you're proposing; is that only a top-level thing? Could you elaborate on that?

> ## III. `*.test.ts(x)` in favor of `__tests__`

I agree, and I believe we're already using that convention (sorry for taking so long to reply 😅).

> ## IV. `package.json` in favor of `index.js`

I don't really like having multiple `package.json`s in a repository that doesn't have smaller, exported packages inside; I don't have very good arguments, it just seems misleading to me.
