### ISSUE TITLE
Widget range doesn`t work on children objects

### ISSUE THREAD

**Issue by Gatamura** [vtex-apps/admin-pages#161]
## Expected Behavior
I need to be able to declare types ui: widget independent of the depth of the object.

## Current Behavior
I have a schema of an object with a string attribute and another array, inside the array I have objects with a string attribute and another array, inside that last internal array I can not call the'ui: widget ':' range 'types, it seems that it ignores this feature of ui: widget and respects only the above type declared as attribute above.

**Comment by alcar** [comment]
Hey, @Gatamura! Sorry for the late reply.

I believe the solution for #106 will also work for you.

I'm closing this issue for now, but please let us know if the problem persists.
