### ISSUE TITLE
Block navigation when edit mode is on

### ISSUE THREAD

**Issue by gabrielgalc** [vtex-apps/admin-pages#20]
## Expected Behavior
You should not be able to navigate through pages when you are editing your site.

## Current Behavior
Now, users are able to navigate through pages when the Pages Editor form is being displayed.

## Steps to Reproduce
1. Install Dreamstore on a store
2. Enter edit mode
3. Click to edit the banner (this will display the Pages Editor form)
4. With the Pages Editor form on, click on another element (a product, for example)

## Context
Pages editor should change the component being edited when the user clicks on another component with the form opened.

**Comment by alcar** [comment]
This issue has already been addressed (#139).
