### ISSUE TITLE
Erro ao fazer hover em algum item editável

### ISSUE THREAD

**Issue by BenevidesLecontes** [vtex-apps/admin-pages#76]
## Expected Behavior
Ao fazer o hover no item editável devia fazer highlight do item
## Current Behavior
![2018-08-20 18 42 43](https://user-images.githubusercontent.com/1839361/44368370-fb288d80-a4a8-11e8-8053-4a4341c1a7ee.gif)

**Comment by brunojdo** [comment]
Oi, você ainda está tendo esse problema?

**Comment by BenevidesLecontes** [comment]
@brunojdo sim

**Comment by brunojdo** [comment]
Pode dizer qual o conta e workspace que o problema ocorre?

**Comment by BenevidesLecontes** [comment]
@brunojdo chillibeans e workspace benevides

**Comment by brunojdo** [comment]
@BenevidesLecontes Sabe me dizer se você está manipulando algum iframe ou tentando injetar codigo em algum componente da sua loja?

**Comment by brunojdo** [comment]
@BenevidesLecontes Seu `pages.json` não está correto e esta estourando a app. 
Você deve usar a `vtex.dreamstore` para criar sua loja.

**Comment by alcar** [comment]
There has been a lot of changes to the code base since the last comment, so I'm closing this issue. Please let us know if the problem persists.
